services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: 'PCt7wo4!'
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - user-service_postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  user-service_postgres_data: